[tool.poetry]
name = "project-test-github"
version = "0.1.0"
description = ""
authors = ["Eduard Gimaev <e.gimaev@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
